export const HOTEL_LIST_REQUEST = "HOTEL_LIST_REQUEST";
export const HOTEL_LIST_SUCCESS = "HOTEL_LIST_SUCCESS";
export const HOTEL_LIST_FAIL = "HOTEL_LIST_FAIL";

export const HOTEL_ADD_REQUEST = "HOTEL_ADD_REQUEST";
export const HOTEL_ADD_SUCCESS = "HOTEL_ADD_SUCCESS";
export const HOTEL_ADD_FAIL = "HOTEL_ADD_FAIL";